### ISSUE TITLE
Add Libreelec dev builds

### ISSUE THREAD

**Issue by polojoe** [LS80/script.openelec.devupdate#28]
Could you add Milhouse Libreelec development builds to your addon?

http://milhouse.libreelec.tv/builds/

**Comment by Mike-KL** [comment]
I second request (Now Krypton LibreElec testbuilds are becoming available) tried to add today http://milhouse.libreelec.tv/builds/master/RPi2 as a custom path in order to install latest #0403 LibreElec Krypton build then update directly from RPi2 as further updates become available but doesn't seem to work.  Currently getting following Kodi warning message

No builds were found for RPi2.arm
http://milhouse.libreelec.tv/builds/master/RPi2
Please check the URL

**Comment by reiniervanrutten** [comment]
Would love this too. Although the addon itself is not working anymore in LibreElec Milhouse Release 418 and automatically disabled by Kodi due to incompatibility.

**Comment by nickrob84** [comment]
I third this request. Is it possible yet?

**Comment by LS80** [comment]
Done with version 4.39.0
